=== agreee45/SNUT/paparazzi/conf/modules/module.dtd
<!-- Paparazzi Modules DTD -->

<!ELEMENT module (depend?,header,init*,periodic*,event*,datalink*,makefile*)>
<!ELEMENT depend EMPTY>
<!ELEMENT header (file*)>
<!ELEMENT init EMPTY>
<!ELEMENT periodic EMPTY>
<!ELEMENT event (handler*)>
<!ELEMENT handler EMPTY>
<!ELEMENT datalink EMPTY>
<!ELEMENT makefile (flag|file|file_hw|define|raw)*>
<!ELEMENT flag EMPTY>
<!ELEMENT file EMPTY>
<!ELEMENT file_hw EMPTY>
<!ELEMENT define EMPTY>
<!ELEMENT raw (#PCDATA)>

<!ATTLIST module
name CDATA #REQUIRED
dir CDATA #IMPLIED>

<!ATTLIST depend
require CDATA #IMPLIED
conflict CDATA #IMPLIED>

<!ATTLIST header>

<!ATTLIST init
fun CDATA #REQUIRED>

<!ATTLIST periodic
fun CDATA #REQUIRED
period CDATA #IMPLIED
freq CDATA #IMPLIED
delay CDATA #IMPLIED
start CDATA #IMPLIED
stop CDATA #IMPLIED
autorun (TRUE|FALSE|LOCK) #IMPLIED >

<!ATTLIST event
fun CDATA #REQUIRED>

<!ATTLIST handler
fun CDATA #REQUIRED>

<!ATTLIST datalink
message CDATA #REQUIRED
fun CDATA #REQUIRED>

<!ATTLIST makefile
target CDATA "ap|sim|jsbsim">

<!ATTLIST flag
name CDATA #REQUIRED
value CDATA #IMPLIED
type CDATA #IMPLIED>

<!ATTLIST file
name CDATA #REQUIRED>

<!ATTLIST file_hw
name CDATA #REQUIRED>

<!ATTLIST define
name CDATA #REQUIRED
value CDATA #REQUIRED>

=== agreee45/SNUT/paparazzi/conf/modules/airspeed_adc.xml
<!DOCTYPE module SYSTEM "module.dtd">

<!--
     Airspeed ADC module
     @param ADC_AIRSPEED on which ADC the sensor is connected
     @param AIRSPEED_SCALE/AIRSPEED_QUADRATIC_SCALE scale factor, quadratic is used if defined
     @param AIRSPEED_BIAS offset on ADC
     -->

<module name="airspeed_adc" dir="sensors">

  <header>
    <file name="airspeed_adc.h"/>
  </header>
  <init fun="airspeed_adc_init()"/>
  <periodic fun="airspeed_adc_update()" freq="10."/>

  <makefile>
    <file name="airspeed_adc.c"/>
  </makefile>
  <makefile target="ap">
    <flag name="ADC_CHANNEL_AIRSPEED" value="$(ADC_AIRSPEED)"/>
    <flag name="USE_$(ADC_AIRSPEED)"/>
  </makefile>

</module>

=== agreee45/SNUT/paparazzi/conf/modules/twog_extra_dl.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="extra_dl" dir="core">
  <header>
    <file name="extra_pprz_dl.h"/>
  </header>
  <event fun="ExtraDatalinkEvent()"/>
  <makefile>
    <flag name="EXTRA_DOWNLINK_DEVICE" value="Uart0"/>
    <flag name="EXTRA_PPRZ_UART" value="Uart0"/>
    <flag name="USE_UART0"/>
    <flag name="UART0_BAUD" value="B57600"/>
    <file name="extra_pprz_dl.c"/>
  </makefile>
</module>

=== agreee45/SNUT/paparazzi/conf/modules/trig_test.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="trigger_ext" dir="core">
  <header>
    <file name="trigger_ext.h"/>
  </header>
  <init fun="trigger_ext_init()"/>
  <makefile>
    <file_hw name="trigger_ext_hw.c"/>
    <file name="trigger_ext.c"/>
    <flag name="TRIGGER_EXT"/>
    <flag name="TRIG_EXT_PULSE_TYPE" value="TRIG_EXT_EDGE_FALLING"/>
  </makefile>
</module>

=== agreee45/SNUT/paparazzi/conf/modules/baro_MS5534A.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="baro_MS5534A" dir="sensors">
  <header>
    <file name="baro_MS5534A.h"/>
  </header>
  <init fun="baro_MS5534A_init()"/>
  <periodic fun="baro_MS5534A_send()" freq="20"/>
  <event fun="baro_MS5534A_event()"/>
  <makefile target="ap">
    <file name="baro_MS5534A.c"/>
    <flag name="USE_BARO_MS5534A"/>
    <flag name="USE_SPI_SLAVE0"/>
    <flag name="SPI_MASTER"/>
    <define name="BARO_MS5534A_W1" value="0xAC20"/>
    <define name="BARO_MS5534A_W2" value="0x87D9"/>
    <define name="BARO_MS5534A_W3" value="0x8D9C"/>
    <define name="BARO_MS5534A_W4" value="0xB080"/>
  </makefile>
</module>

=== agreee45/SNUT/paparazzi/conf/modules/booz_drop.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="drop">
  <!-- depend require="booz_pwm" -->
  <header>
    <file name="booz_drop.h"/>
  </header>
  <init fun="booz_drop_init()"/>
  <periodic fun="booz_drop_periodic()" freq="10."/>
  <makefile>
    <flag name="USE_DROP"/>
    <flag name="DROP_SERVO_OPEN" value="2120"/>
    <flag name="DROP_SERVO_CLOSED" value="1060"/>
    <file name="booz_drop.c"/>
  </makefile>
</module>

=== agreee45/SNUT/paparazzi/conf/modules/airspeed_ets.xml
<!DOCTYPE module SYSTEM "module.dtd">

<!--
     Airspeed ETS module (I2C)
     @param AIRSPEED_ETS_SCALE scale factor (default 1.8)
     @param AIRSPEED_ETS_OFFSET offset (default 0)
     @param AIRSPEED_ETS_I2C_DEV i2c device (default i2c0)
     @flag USE_AIRSPEED to use the data for airspeed control loop
     @flag SENSOR_SYNC_SEND to transmit the data as it is acquired
     -->

<module name="airspeed_ets" dir="sensors">

  <header>
    <file name="airspeed_ets.h"/>
  </header>
  <init fun="airspeed_ets_init()"/>
  <periodic fun="airspeed_ets_read_periodic()" freq="10."/>
  <event fun="AirspeedEtsEvent()"/>

  <makefile>
    <file name="airspeed_ets.c"/>
  </makefile>

</module>

=== agreee45/SNUT/paparazzi/conf/modules/humid_sht_i2c.xml
<!DOCTYPE module SYSTEM "module.dtd">

<!--
     Sensirion SHT25 humidity sensor (I2C)
     @param SCP_I2C_DEV i2c device (default i2c0)
     -->

<module name="humid_sht_i2c" dir="meteo">
  <header>
    <file name="humid_sht_i2c.h"/>
  </header>
  <init fun="humid_sht_init()"/>
  <periodic fun="humid_sht_periodic()" freq="4"/>
  <periodic fun="humid_sht_p_temp()" freq="4" delay="6"/>
  <periodic fun="humid_sht_p_humid()"  freq="4" delay="9"/>
  <event fun="humid_sht_event()"/>
  <makefile target="ap">
    <file name="humid_sht_i2c.c"/>
  </makefile>
</module>

=== agreee45/SNUT/paparazzi/conf/modules/cam_point.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="cam_point" dir="cam_control">
  <header>
    <file name="cam.h"/>
    <file name="point.h"/>
  </header>
  <init fun="cam_init()"/>
  <periodic fun="cam_periodic()" freq="10."/>
  <makefile>
    <flag name="CAM"/>
    <flag name="MOBILE_CAM"/>
    <flag name="POINT_CAM"/>
    <file name="cam.c"/>
    <file name="point.c"/>
  </makefile>
</module>
