=== agreee45/SNUT/paparazzi/conf/modules/module.dtd
<!-- Paparazzi Modules DTD -->

<!ELEMENT module (depend?,header,init*,periodic*,event*,datalink*,makefile*)>
<!ELEMENT depend EMPTY>
<!ELEMENT header (file*)>
<!ELEMENT init EMPTY>
<!ELEMENT periodic EMPTY>
<!ELEMENT event (handler*)>
<!ELEMENT handler EMPTY>
<!ELEMENT datalink EMPTY>
<!ELEMENT makefile (flag|file|file_hw|define|raw)*>
<!ELEMENT flag EMPTY>
<!ELEMENT file EMPTY>
<!ELEMENT file_hw EMPTY>
<!ELEMENT define EMPTY>
<!ELEMENT raw (#PCDATA)>

<!ATTLIST module
name CDATA #REQUIRED
dir CDATA #IMPLIED>

<!ATTLIST depend
require CDATA #IMPLIED
conflict CDATA #IMPLIED>

<!ATTLIST header>

<!ATTLIST init
fun CDATA #REQUIRED>

<!ATTLIST periodic
fun CDATA #REQUIRED
period CDATA #IMPLIED
freq CDATA #IMPLIED
delay CDATA #IMPLIED
start CDATA #IMPLIED
stop CDATA #IMPLIED
autorun (TRUE|FALSE|LOCK) #IMPLIED >

<!ATTLIST event
fun CDATA #REQUIRED>

<!ATTLIST handler
fun CDATA #REQUIRED>

<!ATTLIST datalink
message CDATA #REQUIRED
fun CDATA #REQUIRED>

<!ATTLIST makefile
target CDATA "ap|sim|jsbsim">

<!ATTLIST flag
name CDATA #REQUIRED
value CDATA #IMPLIED
type CDATA #IMPLIED>

<!ATTLIST file
name CDATA #REQUIRED>

<!ATTLIST file_hw
name CDATA #REQUIRED>

<!ATTLIST define
name CDATA #REQUIRED
value CDATA #REQUIRED>

=== agreee45/SNUT/paparazzi/conf/modules/adc_generic.xml
<!DOCTYPE module SYSTEM "module.dtd">

<!--
     Generic ADC module
     @param ADC_CHANNEL_GENERIC1 on which ADC input 1 is measured
     @param ADC_CHANNEL_GENERIC2 on which ADC input 2 is measured
     -->

<module name="adc_generic" dir="adcs">
  <header>
    <file name="adc_generic.h"/>
  </header>
  <init fun="adc_generic_init()"/>
  <periodic fun="adc_generic_periodic()" freq="4"/>
  <makefile target="ap">
    <file name="adc_generic.c"/>
    <flag name="USE_$(ADC_CHANNEL_GENERIC1)"/>
    <flag name="USE_$(ADC_CHANNEL_GENERIC2)"/>
  </makefile>
</module>

=== agreee45/SNUT/paparazzi/conf/modules/baro_scp.xml
<!DOCTYPE module SYSTEM "module.dtd">

<!--
     VTI SCP1000 pressure sensor (SPI)
     @flag SENSOR_SYNC_SEND to transmit the data as it is acquired
     -->

<module name="baro_scp" dir="sensors">
  <header>
    <file name="baro_scp.h"/>
  </header>
  <init fun="baro_scp_init()"/>
  <periodic fun="baro_scp_periodic()" freq="1.8"/>
  <event fun="baro_scp_event()"/>
  <makefile target="ap">
    <file name="baro_scp.c"/>
    <flag name="SPI_MASTER"/>
    <flag name="USE_SPI"/>
  </makefile>
</module>

=== agreee45/SNUT/paparazzi/conf/modules/windturbine.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="windturbine" dir="meteo">
  <depend require="trig_test.xml"/>
  <header>
    <file name="windturbine.h"/>
  </header>
  <periodic fun="windturbine_periodic()" freq="10"/>
  <makefile>
    <file name="windturbine.c"/>
    <flag name="TURBINE_ID" value="42"/>
    <flag name="GPS_TIMESTAMP"/>
  </makefile>
</module>
