=== agreee45/SNUT/paparazzi/conf/modules/module.dtd
<!-- Paparazzi Modules DTD -->

<!ELEMENT module (depend?,header,init*,periodic*,event*,datalink*,makefile*)>
<!ELEMENT depend EMPTY>
<!ELEMENT header (file*)>
<!ELEMENT init EMPTY>
<!ELEMENT periodic EMPTY>
<!ELEMENT event (handler*)>
<!ELEMENT handler EMPTY>
<!ELEMENT datalink EMPTY>
<!ELEMENT makefile (flag|file|file_hw|define|raw)*>
<!ELEMENT flag EMPTY>
<!ELEMENT file EMPTY>
<!ELEMENT file_hw EMPTY>
<!ELEMENT define EMPTY>
<!ELEMENT raw (#PCDATA)>

<!ATTLIST module
name CDATA #REQUIRED
dir CDATA #IMPLIED>

<!ATTLIST depend
require CDATA #IMPLIED
conflict CDATA #IMPLIED>

<!ATTLIST header>

<!ATTLIST init
fun CDATA #REQUIRED>

<!ATTLIST periodic
fun CDATA #REQUIRED
period CDATA #IMPLIED
freq CDATA #IMPLIED
delay CDATA #IMPLIED
start CDATA #IMPLIED
stop CDATA #IMPLIED
autorun (TRUE|FALSE|LOCK) #IMPLIED >

<!ATTLIST event
fun CDATA #REQUIRED>

<!ATTLIST handler
fun CDATA #REQUIRED>

<!ATTLIST datalink
message CDATA #REQUIRED
fun CDATA #REQUIRED>

<!ATTLIST makefile
target CDATA "ap|sim|jsbsim">

<!ATTLIST flag
name CDATA #REQUIRED
value CDATA #IMPLIED
type CDATA #IMPLIED>

<!ATTLIST file
name CDATA #REQUIRED>

<!ATTLIST file_hw
name CDATA #REQUIRED>

<!ATTLIST define
name CDATA #REQUIRED
value CDATA #REQUIRED>

=== agreee45/SNUT/paparazzi/conf/modules/booz_extra_dl.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="core">
  <header>
    <file name="extra_pprz_dl.h"/>
  </header>
  <event fun="ExtraDatalinkEvent()"/>
  <makefile>
    <flag name="EXTRA_DOWNLINK_DEVICE" value="Uart0"/>
    <flag name="EXTRA_PPRZ_UART" value="Uart0"/>
    <flag name="USE_UART0"/>
    <flag name="UART0_BAUD" value="B57600"/>
    <flag name="UART0_VIC_SLOT" value="5"/>
    <file name="extra_pprz_dl.c"/>
  </makefile>
</module>

=== agreee45/SNUT/paparazzi/conf/modules/ins_xsens_MTi_Uart0.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="ins">
  <!-- <depend conflict="ins" -->
  <header>
    <file name="ins_module.h"/>
  </header>
  <init fun="ins_init()"/>
  <periodic fun="ins_periodic_task()" freq="60"/>
  <makefile>
    <flag name="USE_UART0"/>
    <flag name="INS_LINK" value="Uart0"/>
    <flag name="UART0_BAUD" value="B115200"/>
    <!-- calibrated, orientation, status -->
    <flag name="XSENS_OUTPUT_MODE" value="0x0806"/>
    <!-- timestamp, euler, acc, rate, mag, float, no aux, NED -->
    <flag name="XSENS_OUTPUT_SETTINGS" value="0x80000C05"/>
    <file name="ins_xsens.c"/>
  </makefile>
</module>

=== agreee45/SNUT/paparazzi/conf/modules/infrared_i2c.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="ir_i2c" dir="sensors">
  <header>
    <file name="infrared_i2c.h"/>
  </header>
  <init fun="infrared_i2c_init()"/>
  <periodic fun="infrared_i2c_update()" freq="60."/>
  <!--periodic fun="infrared_i2cDownlink()" freq="1."/-->
  <event fun="infrared_i2cEvent()"/>
  <makefile>
    <flag name="INFRARED_I2C"/>
    <file name="infrared_i2c.c"/>
  </makefile>
  <makefile target="sim">
    <raw>sim.srcs += $(SRC_ARCH)/sim_ir.c</raw>
  </makefile>
</module>

=== agreee45/SNUT/paparazzi/conf/modules/digital_cam.xml
<!DOCTYPE module SYSTEM "./module.dtd">

<!-- 

// Use (parts of) the following section in airframe file to change 

  <section name="DIGITAL_CAMERA" prefix="DC_">

    <define name="PUSH" value"LED_ON" />
    <define name="RELEASE" value"LED_OFF" />

    <define name="AUTOSHOOT_QUARTERSEC_PERIOD" value="6" unit="quarter_second"/>
    <define name="AUTOSHOOT_METER_GRID" value="50" unit="meter"/>
  </section>

# ap.CFLAGS += -DGPS_TRIGGERED_FUNCTION="dc_shoot_on_gps" 
# ap.CFLAGS += -DDC_GPS_TRIGGER_START=1 
# ap.CFLAGS += -DDC_GPS_TRIGGER_STOP=3 

-->

<module name="digital_cam">
  <header>
    <file name="led_cam_ctrl.h"/>
  </header>

  <init fun="led_cam_ctrl_init()"/>

  <periodic fun="led_cam_ctrl_periodic()" freq="4" autorun="TRUE"/>

  <makefile >

    <flag name="DIGITAL_CAM" />
    <file name="led_cam_ctrl.c"/>
    <file name="dc.c"/>
      <flag name="SENSOR_SYNC_SEND" value="1" />

  </makefile>


</module>

=== agreee45/SNUT/paparazzi/conf/modules/vehicle_interface_overo_link.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="vi_overo_link" dir="vehicle_interface">
  <header>
    <file name="vi_overo_link.h"/>
  </header>
  <init fun="vi_init()"/>
  <periodic fun="vi_periodic()"/>
  <event fun="ViOveroLinkEvent()"/>
  <makefile>
    <file name="vi.c"/>
    <file name="vi_overo_link.c"/>
  </makefile>
  <makefile target="ap">
    <raw>ap.srcs   += lisa/lisa_overo_link.c lisa/arch/stm32/lisa_overo_link_arch.c</raw>
    <flag name="USE_VEHICLE_INTERFACE"/>
    <flag name="USE_OVERO_LINK"/>
    <flag name="lisa/arch/stm32" type="include"/>
    <flag name="OVERO_LINK_MSG_UP" value="AutopilotMessageVIUp"/>
    <flag name="OVERO_LINK_MSG_DOWN" value="AutopilotMessageVIDown"/>
    <flag name="OVERO_LINK_LED_OK" value="3"/>
    <flag name="OVERO_LINK_LED_KO" value="2"/>
    <flag name="USE_DMA1_C2_IRQ"/>
  </makefile>
</module>

=== agreee45/SNUT/paparazzi/conf/modules/trigger_ext.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="trigger_ext" dir="sensors">
  <header>
    <file name="trig_ext_hw.h"/>
    <file name="trigger_ext.h"/>
  </header>
  <init fun="trigger_ext_init()"/>
  <periodic fun="trigger_ext_periodic()" freq="10"/>
  <makefile>
    <file_hw name="trig_ext_hw.c"/>
    <file name="trigger_ext.c"/>
    <flag name="TRIGGER_EXT"/>
    <flag name="TRIG_EXT_PULSE_TYPE" value="TRIG_EXT_EDGE_FALLING"/>
    <flag name="TURBINE_ID" value="42"/>
    <flag name="GPS_TIMESTAMP"/>
  </makefile>
</module>

=== agreee45/SNUT/paparazzi/conf/modules/ins_xsens_MTiG_fixedwing.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="ins">
  <!-- <depend conflict="ins" -->
  <!-- <depend require="gps_xsens" -->
  <header>
    <file name="ins_module.h"/>
  </header>
  <init fun="ins_init()"/>
  <periodic fun="ins_periodic_task()" freq="60"/>
  <event fun="InsEventCheckAndHandle(handle_ins_msg())"/>
  <makefile>
    <flag name="USE_UART1"/>
    <flag name="INS_LINK" value="Uart1"/>
    <flag name="UART1_BAUD" value="B115200"/>
    <flag name="USE_GPS_XSENS"/>
    <flag name="USE_GPS_XSENS_RAW_DATA" />
    <file name="ins_xsens.c"/>
  </makefile>
</module>

=== agreee45/SNUT/paparazzi/conf/modules/sonar_maxbotix_booz.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="sonar">
  <header>
    <file name="sonar_maxbotix_booz.h"/>
  </header>
  <init fun="maxbotix_init()"/>
  <periodic fun="maxbotix_read()" freq="10"/>
  <event fun="SonarEvent(ins_update_sonar)"/>
  <makefile target="ap">
    <flag name="USE_EXTRA_ADC"/>
    <flag name="USE_ADC_1"/>
    <flag name="BOOZ2_SONAR"/>
    <file name="sonar_maxbotix_booz.c"/>
  </makefile>
</module>
